movement_core:
  diagram_variables:
    m1:
      - 0
      - 0
      - 0
    a1:
      - 0.0676
      - 0
      - 0
    a2:
      - 0.09237
      - 0
      - 0
    a3:
      - 0.22524
      - 0
      - 0